version: "3"
services:
  ddl-judge-dev:
    command: celery -A tasks worker -l info -Q judge
    volumes:
      - ~/data/ddl-backend/test_cases:/judge/test_cases
    image: 4ddl/ddlcw
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ddl-judge-dev
    restart: always
    environment:
      - BACKEND_URL=http://127.0.0.1
      - BROKER_URL=amqp://guest:guest@127.0.0.1:5672/
      - DDLCW_DEBUG=True
      - DDLCW_SYNC_ENABLE=True
      - JUDGE_TOKEN=JUDGE_TOKEN